INSERT INTO Categoria VALUES (2,'Biscuits et gâteaux');
INSERT INTO Categoria VALUES (3,'Biscuits');
INSERT INTO Categoria VALUES (4,'Biscuits au chocolat');
INSERT INTO Categoria VALUES (5,'en:sugary-snacks');
INSERT INTO Categoria VALUES (6,'en:biscuits-and-cakes');
INSERT INTO Categoria VALUES (7,'en:biscuits');
INSERT INTO Categoria VALUES (8,'fr:speculoos');
INSERT INTO Categoria VALUES (9,'Aliments et boissons à base de végétaux');
INSERT INTO Categoria VALUES (10,'Aliments d''origine végétale');
INSERT INTO Categoria VALUES (11,'Céréales et pommes de terre');
INSERT INTO Categoria VALUES (12,'Pains');
INSERT INTO Categoria VALUES (13,'Gressins');
INSERT INTO Categoria VALUES (14,'en:salty-snacks');
INSERT INTO Categoria VALUES (15,'en:appetizers');
INSERT INTO Categoria VALUES (16,'en:chips-and-fries');
INSERT INTO Categoria VALUES (17,'en:crisps');
INSERT INTO Categoria VALUES (18,'en:corn-chips');
INSERT INTO Categoria VALUES (19,'Snacks sucrés');
INSERT INTO Categoria VALUES (20,'Petits beurres');
INSERT INTO Categoria VALUES (21,'fr:Biscuits apéritif soufflés');
INSERT INTO Categoria VALUES (22,'fr:Biscuits apéritif soufflés à la cacahuète');
INSERT INTO Categoria VALUES (23,'Cookies');
INSERT INTO Categoria VALUES (24,'Cookies au chocolat');
INSERT INTO Categoria VALUES (25,'Céréales et dérivés');
INSERT INTO Categoria VALUES (26,'Galettes de céréales');
INSERT INTO Categoria VALUES (27,'Galettes de riz');
INSERT INTO Categoria VALUES (28,'Galettes de riz au chocolat noir');
INSERT INTO Categoria VALUES (29,'Viandes');
INSERT INTO Categoria VALUES (30,'Charcuteries');
INSERT INTO Categoria VALUES (31,'Saucissons');
INSERT INTO Categoria VALUES (32,'Saucissons secs');
INSERT INTO Categoria VALUES (33,'Saucissons secs aux noisettes');
INSERT INTO Categoria VALUES (34,'Galettes de riz au chocolat au lait');
INSERT INTO Categoria VALUES (35,'en:plant-based-foods-and-beverages');
INSERT INTO Categoria VALUES (36,'en:plant-based-foods');
INSERT INTO Categoria VALUES (37,'en:cereals-and-potatoes');
INSERT INTO Categoria VALUES (38,'en:breads');
INSERT INTO Categoria VALUES (39,'en:special-breads');
INSERT INTO Categoria VALUES (40,'Crêpes et galettes');
INSERT INTO Categoria VALUES (41,'Crêpes');
INSERT INTO Categoria VALUES (42,'Crêpes dentelle');
INSERT INTO Categoria VALUES (43,'Chocolats');
INSERT INTO Categoria VALUES (44,'Chocolats noirs');
INSERT INTO Categoria VALUES (45,'Biscuits au chocolat au lait');
INSERT INTO Categoria VALUES (46,'Crêpes fourrées');
INSERT INTO Categoria VALUES (47,'Crêpes sucrées');
INSERT INTO Categoria VALUES (48,'Digestive Biscuits');
INSERT INTO Categoria VALUES (49,'Gaufres');
INSERT INTO Categoria VALUES (50,'Gaufrettes');
INSERT INTO Categoria VALUES (51,'Biscuits-aux-cereales');
INSERT INTO Categoria VALUES (52,'Biscuits-bio');
INSERT INTO Categoria VALUES (53,'Biscuits secs');
INSERT INTO Categoria VALUES (54,'Galettes-bretonnes');
INSERT INTO Categoria VALUES (55,'Galettes bretonnes');
INSERT INTO Categoria VALUES (56,'Chips de légumes');
INSERT INTO Categoria VALUES (57,'chips');
INSERT INTO Categoria VALUES (58,'Confiseries');
INSERT INTO Categoria VALUES (59,'Caramels');
INSERT INTO Categoria VALUES (60,'Caramels au beurre salé');
INSERT INTO Categoria VALUES (61,'Crème de caramel');
INSERT INTO Categoria VALUES (62,'Biscuits sablés');
INSERT INTO Categoria VALUES (63,'Sugary snacks');
INSERT INTO Categoria VALUES (64,'Biscuits and cakes');
INSERT INTO Categoria VALUES (65,'Sablés');
INSERT INTO Categoria VALUES (66,'Aliments à base de fruits et de légumes');
INSERT INTO Categoria VALUES (67,'Fruits et produits dérivés');
INSERT INTO Categoria VALUES (68,'Produits déshydratés');
INSERT INTO Categoria VALUES (69,'Aliments à base de plantes séchés');
INSERT INTO Categoria VALUES (70,'Fruits secs');
INSERT INTO Categoria VALUES (71,'Mélanges de fruits secs');
INSERT INTO Categoria VALUES (72,'Biscuits apéritifs');
INSERT INTO Categoria VALUES (73,'Snacks salés');
INSERT INTO Categoria VALUES (74,'Gressins artisanaux');
INSERT INTO Categoria VALUES (75,'Saucissons de boeuf');
INSERT INTO Categoria VALUES (76,'Macaron à la framboise');
INSERT INTO Categoria VALUES (77,'Goûters fourrés');
INSERT INTO Categoria VALUES (78,'Apéritif');
INSERT INTO Categoria VALUES (79,'Chips et frites');
INSERT INTO Categoria VALUES (80,'Chips');
INSERT INTO Categoria VALUES (81,'Chips de pommes de terre');
INSERT INTO Categoria VALUES (82,'Chips de pommes de terre à l''huile de tournesol');
INSERT INTO Categoria VALUES (83,'en:aperitif');
INSERT INTO Categoria VALUES (84,'en:biscuits-aperitifs');
INSERT INTO Categoria VALUES (85,'en:snacks-sales');
INSERT INTO Categoria VALUES (86,'nl:Zoute snacks');
INSERT INTO Categoria VALUES (87,'Surgelés');
INSERT INTO Categoria VALUES (88,'Biscuits feuilletés');
INSERT INTO Categoria VALUES (89,'Palmiers');
INSERT INTO Categoria VALUES (90,'Biscuits au beurre');
INSERT INTO Categoria VALUES (91,'Desserts');
INSERT INTO Categoria VALUES (92,'Gâteaux');
INSERT INTO Categoria VALUES (93,'Gâteaux au chocolat');
INSERT INTO Categoria VALUES (94,'Chips de pommes de terre allégées');
INSERT INTO Categoria VALUES (95,'Brownies');
INSERT INTO Categoria VALUES (96,'Muesli Bars');
INSERT INTO Categoria VALUES (97,'Chips de maïs');
INSERT INTO Categoria VALUES (98,'Aperitivos');
INSERT INTO Categoria VALUES (99,'Aros de maíz');
INSERT INTO Categoria VALUES (100,'Beurres demi-sel');
INSERT INTO Categoria VALUES (101,'Beurres pasteurisés');
INSERT INTO Categoria VALUES (102,'Biscuits au chocolat noir');
INSERT INTO Categoria VALUES (103,'Conserves');
INSERT INTO Categoria VALUES (104,'Poissons et viandes et oeufs');
INSERT INTO Categoria VALUES (105,'Foies gras');
INSERT INTO Categoria VALUES (106,'Bloc de foie gras');
INSERT INTO Categoria VALUES (107,'Foies gras de canard');
INSERT INTO Categoria VALUES (108,'Foie gras de canard au porto');
INSERT INTO Categoria VALUES (109,'Chorizos');
INSERT INTO Categoria VALUES (110,'Blocs de foie gras');
INSERT INTO Categoria VALUES (111,'Snacks dulces');
INSERT INTO Categoria VALUES (112,'Dulces');
INSERT INTO Categoria VALUES (113,'Gastronomía navideña');
INSERT INTO Categoria VALUES (114,'Dulces de Navidad');
INSERT INTO Categoria VALUES (115,'Mazapanes');
INSERT INTO Categoria VALUES (116,'Figuritas de mazapán');
INSERT INTO Categoria VALUES (117,'Salty snacks');
INSERT INTO Categoria VALUES (118,'Erdnüsse');
INSERT INTO Categoria VALUES (119,'Chocolats au lait');
INSERT INTO Categoria VALUES (120,'Chocolat au lait fourré');
INSERT INTO Categoria VALUES (121,'Marzipan');
INSERT INTO Categoria VALUES (122,'Appetizers');
INSERT INTO Categoria VALUES (123,'Chips and fries');
INSERT INTO Categoria VALUES (124,'Crisps');
INSERT INTO Categoria VALUES (125,'Corn chips');
INSERT INTO Categoria VALUES (126,'Plant-based foods and beverages');
INSERT INTO Categoria VALUES (127,'Plant-based foods');
INSERT INTO Categoria VALUES (128,'Nuts and their products');
INSERT INTO Categoria VALUES (129,'Bars');
INSERT INTO Categoria VALUES (130,'Nut bars');
INSERT INTO Categoria VALUES (131,'Museli bars');
INSERT INTO Categoria VALUES (132,'biscuits au beurre');
INSERT INTO Categoria VALUES (133,'sablés');
INSERT INTO Categoria VALUES (134,'gâteaux bretons');
INSERT INTO Categoria VALUES (135,'palets bretons');
INSERT INTO Categoria VALUES (136,'Epicerie');
INSERT INTO Categoria VALUES (137,'Sauces');
INSERT INTO Categoria VALUES (138,'Sauces pour pâtes');
INSERT INTO Categoria VALUES (139,'Sauces Pesto');
INSERT INTO Categoria VALUES (140,'Sauces Pesto Rosso');
INSERT INTO Categoria VALUES (141,'Bonbons');
INSERT INTO Categoria VALUES (142,'Saucisses');
INSERT INTO Categoria VALUES (143,'Chocolats fourrés au caramel');
INSERT INTO Categoria VALUES (144,'Alimentos y bebidas de origen vegetal');
INSERT INTO Categoria VALUES (145,'Alimentos de origen vegetal');
INSERT INTO Categoria VALUES (146,'Cereales y patatas');
INSERT INTO Categoria VALUES (147,'Cereales y derivados');
INSERT INTO Categoria VALUES (148,'Tortitas de cereales');
INSERT INTO Categoria VALUES (149,'Tortitas de maíz');
INSERT INTO Categoria VALUES (150,'Chocolates');
INSERT INTO Categoria VALUES (151,'Milk chocolates');
INSERT INTO Categoria VALUES (152,'fr:Biscuits sablés');
INSERT INTO Categoria VALUES (153,'fr:Biscuits pur beurre');
INSERT INTO Categoria VALUES (154,'fr:Galettes bretonnes');
INSERT INTO Categoria VALUES (155,'Frutos de cáscara y derivados');
INSERT INTO Categoria VALUES (156,'Dulces de frutos de cáscara');
INSERT INTO Categoria VALUES (157,'Almendras garrapiñadas');
INSERT INTO Categoria VALUES (158,'Barres');
INSERT INTO Categoria VALUES (159,'Barres de céréales');
INSERT INTO Categoria VALUES (160,'fr:Barres');
INSERT INTO Categoria VALUES (161,'fr:Barres chocolatées');
INSERT INTO Categoria VALUES (162,'Candies');
INSERT INTO Categoria VALUES (163,'Barres chocolatées');
INSERT INTO Categoria VALUES (164,'Barritas');
INSERT INTO Categoria VALUES (165,'Barritas de cereales');
INSERT INTO Categoria VALUES (166,'Sonnenblumenkerne');
INSERT INTO Categoria VALUES (167,'Biscuits aux céréales');
INSERT INTO Categoria VALUES (168,'Biscuits salés');
INSERT INTO Categoria VALUES (169,'Blocs de foies gras avec morceaux');
INSERT INTO Categoria VALUES (170,'Bloc de foie gras avec morceaux');
INSERT INTO Categoria VALUES (171,'Foies gras cuits');
INSERT INTO Categoria VALUES (172,'Foies gras mi-cuits');
INSERT INTO Categoria VALUES (173,'sweet biscuits');
INSERT INTO Categoria VALUES (174,'Chocolate Bars');
INSERT INTO Categoria VALUES (175,'Chocolate biscuits');
INSERT INTO Categoria VALUES (176,'Chocolates rellenos de crema de menta');
INSERT INTO Categoria VALUES (177,'Coppa');
INSERT INTO Categoria VALUES (178,'Crackers');
INSERT INTO Categoria VALUES (179,'Sauce');
INSERT INTO Categoria VALUES (180,'Leguminosas y derivados');
INSERT INTO Categoria VALUES (181,'Untables');
INSERT INTO Categoria VALUES (182,'Untables vegetales');
INSERT INTO Categoria VALUES (183,'Purés de oleaginosas');
INSERT INTO Categoria VALUES (184,'Mantecas de frutos de cáscara');
INSERT INTO Categoria VALUES (185,'Mantecas de leguminosas');
INSERT INTO Categoria VALUES (186,'Mantecas de cacahuete');
INSERT INTO Categoria VALUES (187,'Cremas de frutos secos');
INSERT INTO Categoria VALUES (188,'Bolachas');
INSERT INTO Categoria VALUES (189,'Kekse');
INSERT INTO Categoria VALUES (190,'Pan y repostería');
INSERT INTO Categoria VALUES (191,'Foies gras entiers');
INSERT INTO Categoria VALUES (192,'Galettes Bretonnes');
INSERT INTO Categoria VALUES (193,'Gâteaux bretons');
INSERT INTO Categoria VALUES (194,'Galettes sablées');
INSERT INTO Categoria VALUES (195,'Galletas y pasteles');
INSERT INTO Categoria VALUES (196,'Galletas');
INSERT INTO Categoria VALUES (197,'Spéculoos');
INSERT INTO Categoria VALUES (198,'Galletas de tipo Digestive');
INSERT INTO Categoria VALUES (199,'Galletas de tipo campurrianas');
INSERT INTO Categoria VALUES (200,'Galletas de tipo María');
INSERT INTO Categoria VALUES (201,'Productos sin gluten');
INSERT INTO Categoria VALUES (202,'Barritas de cereales sin gluten');
INSERT INTO Categoria VALUES (203,'Breadsticks');
INSERT INTO Categoria VALUES (204,'Dressing');
INSERT INTO Categoria VALUES (205,'Pflanzliche Lebensmittel und Getränke');
INSERT INTO Categoria VALUES (206,'Pflanzliche Lebensmittel');
INSERT INTO Categoria VALUES (207,'Frucht- und gemüsebasierte Lebensmittel');
INSERT INTO Categoria VALUES (208,'Fruchtbasierte Lebensmittel');
INSERT INTO Categoria VALUES (209,'Gaufres fourrées');
INSERT INTO Categoria VALUES (210,'Galettes au chocolat');
INSERT INTO Categoria VALUES (211,'Vinaigrettes');
INSERT INTO Categoria VALUES (212,'Dragées');
INSERT INTO Categoria VALUES (213,'Confectioneries');
INSERT INTO Categoria VALUES (214,'Chocolate bars');
INSERT INTO Categoria VALUES (215,'Süßwaren');
INSERT INTO Categoria VALUES (216,'Christmas foods and drinks');
INSERT INTO Categoria VALUES (217,'Christmas sweets');
INSERT INTO Categoria VALUES (218,'Mayonesas');
INSERT INTO Categoria VALUES (219,'Groceries');
INSERT INTO Categoria VALUES (220,'Salsas');
INSERT INTO Categoria VALUES (221,'Mayonesas sin huevo');
INSERT INTO Categoria VALUES (222,'Mazapanes de Soto');
INSERT INTO Categoria VALUES (223,'Croutons');
INSERT INTO Categoria VALUES (224,'Crêpes au chocolat');
INSERT INTO Categoria VALUES (225,'Frais');
INSERT INTO Categoria VALUES (226,'Mini saucissons secs');
INSERT INTO Categoria VALUES (227,'Biscuits bretons');
INSERT INTO Categoria VALUES (228,'Biscuits apéritifs soufflés');
INSERT INTO Categoria VALUES (229,'Saucisson aux noix');
INSERT INTO Categoria VALUES (230,'Schokoladen');
INSERT INTO Categoria VALUES (231,'Chocolate cookies');
INSERT INTO Categoria VALUES (232,'fr:Biscuits apéritif soufflés au bacon');
INSERT INTO Categoria VALUES (233,'Biscuits apéritif soufflés au bacon');
