INSERT INTO Embalagem VALUES (2,'sachet plastique individuel');
INSERT INTO Embalagem VALUES (3,'paquet');
INSERT INTO Embalagem VALUES (4,'Plastique');
INSERT INTO Embalagem VALUES (5,'sachet');
INSERT INTO Embalagem VALUES (6,'en:carton');
INSERT INTO Embalagem VALUES (7,'fr:Film plastique à jeter');
INSERT INTO Embalagem VALUES (8,'fr:Étui carton à recycler');
INSERT INTO Embalagem VALUES (9,'fr:Pensez au tri!');
INSERT INTO Embalagem VALUES (10,'en:Green dot');
INSERT INTO Embalagem VALUES (11,'en:Triman');
INSERT INTO Embalagem VALUES (12,'Carton');
INSERT INTO Embalagem VALUES (13,'carton');
INSERT INTO Embalagem VALUES (14,'Bolsa de aluminio');
INSERT INTO Embalagem VALUES (15,'Sachet');
INSERT INTO Embalagem VALUES (16,'Sachet plastique');
INSERT INTO Embalagem VALUES (17,'sachet plastique');
INSERT INTO Embalagem VALUES (18,'Boîte');
INSERT INTO Embalagem VALUES (19,'Barquette');
INSERT INTO Embalagem VALUES (20,'Film plastique');
INSERT INTO Embalagem VALUES (21,'Film plastique à jeter');
INSERT INTO Embalagem VALUES (22,'Boite à recycler');
INSERT INTO Embalagem VALUES (23,'Film à jeter');
INSERT INTO Embalagem VALUES (24,'plastique');
INSERT INTO Embalagem VALUES (25,'Tablette');
INSERT INTO Embalagem VALUES (26,'Sachet individuel');
INSERT INTO Embalagem VALUES (27,'Box');
INSERT INTO Embalagem VALUES (28,'6 sachets fraîcheur');
INSERT INTO Embalagem VALUES (29,'Papier');
INSERT INTO Embalagem VALUES (30,'Film');
INSERT INTO Embalagem VALUES (31,'Flacon');
INSERT INTO Embalagem VALUES (32,'Pot');
INSERT INTO Embalagem VALUES (33,'Verre');
INSERT INTO Embalagem VALUES (34,'boîte');
INSERT INTO Embalagem VALUES (35,'Sachet plastique à jeter');
INSERT INTO Embalagem VALUES (36,'Étui carton à recycler');
INSERT INTO Embalagem VALUES (37,'Barquette et film plastique à jeter');
INSERT INTO Embalagem VALUES (38,'Etui carton à recycler');
INSERT INTO Embalagem VALUES (39,'Sachets plastiques');
INSERT INTO Embalagem VALUES (40,'étui carton');
INSERT INTO Embalagem VALUES (41,'Triman');
INSERT INTO Embalagem VALUES (42,'Point vert');
INSERT INTO Embalagem VALUES (43,'nl:sachet');
INSERT INTO Embalagem VALUES (44,'nl:plastique');
INSERT INTO Embalagem VALUES (45,'nl:Plastiek');
INSERT INTO Embalagem VALUES (46,'Boite');
INSERT INTO Embalagem VALUES (47,'Surgelé');
INSERT INTO Embalagem VALUES (48,'Sachets plastiques à jeter');
INSERT INTO Embalagem VALUES (49,'Etui');
INSERT INTO Embalagem VALUES (50,'Sachets plastique à jeter');
INSERT INTO Embalagem VALUES (51,'cardboard');
INSERT INTO Embalagem VALUES (52,'box');
INSERT INTO Embalagem VALUES (53,'foil');
INSERT INTO Embalagem VALUES (54,'Bolsa de plástico y aluminio');
INSERT INTO Embalagem VALUES (55,'Frais');
INSERT INTO Embalagem VALUES (56,'étui');
INSERT INTO Embalagem VALUES (57,'conserve');
INSERT INTO Embalagem VALUES (58,'Sous atmosphère protectrice');
INSERT INTO Embalagem VALUES (59,'coque plastique');
INSERT INTO Embalagem VALUES (60,'étiquette papier');
INSERT INTO Embalagem VALUES (61,'opercule papier alu');
INSERT INTO Embalagem VALUES (62,'Sachet Cellophane');
INSERT INTO Embalagem VALUES (63,'Bolsa de plástico');
INSERT INTO Embalagem VALUES (64,'Caja de cartón');
INSERT INTO Embalagem VALUES (65,'Kunststoff');
INSERT INTO Embalagem VALUES (66,'papier');
INSERT INTO Embalagem VALUES (67,'aluminium');
INSERT INTO Embalagem VALUES (68,'Karton');
INSERT INTO Embalagem VALUES (69,'21 PAP');
INSERT INTO Embalagem VALUES (70,'1 PET');
INSERT INTO Embalagem VALUES (71,'sachets fraicheurs');
INSERT INTO Embalagem VALUES (72,'Couvercle');
INSERT INTO Embalagem VALUES (73,'Métal');
INSERT INTO Embalagem VALUES (74,'Conserve');
INSERT INTO Embalagem VALUES (75,'Bouteille');
INSERT INTO Embalagem VALUES (76,'paper wrap');
INSERT INTO Embalagem VALUES (77,'metal wrap');
INSERT INTO Embalagem VALUES (78,'Plástico');
INSERT INTO Embalagem VALUES (79,'Caja');
INSERT INTO Embalagem VALUES (80,'Cartón');
INSERT INTO Embalagem VALUES (81,'05 PP');
INSERT INTO Embalagem VALUES (82,'♷');
INSERT INTO Embalagem VALUES (83,'Emballage individuel plastique à jeter');
INSERT INTO Embalagem VALUES (84,'Sac');
INSERT INTO Embalagem VALUES (85,'4 Sachets de 5 biscuits');
INSERT INTO Embalagem VALUES (86,'barquette');
INSERT INTO Embalagem VALUES (87,'opercule');
INSERT INTO Embalagem VALUES (88,'métal');
INSERT INTO Embalagem VALUES (89,'bocal');
INSERT INTO Embalagem VALUES (90,'verre');
INSERT INTO Embalagem VALUES (91,'frais');
INSERT INTO Embalagem VALUES (92,'sous vide');
INSERT INTO Embalagem VALUES (93,'Barquette aluminium');
INSERT INTO Embalagem VALUES (94,'Plastic');
INSERT INTO Embalagem VALUES (95,'sachet papier');
INSERT INTO Embalagem VALUES (96,'Envoltorio de plástico');
INSERT INTO Embalagem VALUES (97,'Soporte de plástico');
INSERT INTO Embalagem VALUES (98,'Adhésif');
INSERT INTO Embalagem VALUES (99,'bottle - plastic');
INSERT INTO Embalagem VALUES (100,'plástico');
INSERT INTO Embalagem VALUES (101,'sacchetto');
INSERT INTO Embalagem VALUES (102,'carta');
INSERT INTO Embalagem VALUES (103,'plastica');
INSERT INTO Embalagem VALUES (104,'Bocal');
INSERT INTO Embalagem VALUES (105,'4 sachets fraîcheurs');
INSERT INTO Embalagem VALUES (106,'4 Sachets de 4 biscuits');
INSERT INTO Embalagem VALUES (107,'Envase metalizado');
INSERT INTO Embalagem VALUES (108,'Bag');
INSERT INTO Embalagem VALUES (109,'90 C/PP');
INSERT INTO Embalagem VALUES (110,'Glass');
INSERT INTO Embalagem VALUES (111,'Bottle');
INSERT INTO Embalagem VALUES (112,'Sachet Individuel');
INSERT INTO Embalagem VALUES (113,'Fer');
INSERT INTO Embalagem VALUES (114,'Plastic zak');
INSERT INTO Embalagem VALUES (115,'Aluminium');
INSERT INTO Embalagem VALUES (116,'Bote de vidrio');
INSERT INTO Embalagem VALUES (117,'Box - card');
INSERT INTO Embalagem VALUES (118,'Boîte carton');
INSERT INTO Embalagem VALUES (119,'Barquette plastique');
INSERT INTO Embalagem VALUES (120,'Sous atmopshère protectrice');
INSERT INTO Embalagem VALUES (121,'Sous papier transparent');
