INSERT INTO Fabricante VALUES (1,'Bjorg');
INSERT INTO Fabricante VALUES (2,'Lotus');
INSERT INTO Fabricante VALUES (3,'Saveurs de nos régions');
INSERT INTO Fabricante VALUES (4,'Carrefour Bio,Carrefour');
INSERT INTO Fabricante VALUES (5,'Carrefour Bio,Carrefour,//Propiedad de://,Carrefour S.A.');
INSERT INTO Fabricante VALUES (6,'Le moulin du pivert');
INSERT INTO Fabricante VALUES (7,'Bonne Maman');
INSERT INTO Fabricante VALUES (8,'Vico,Intersnack');
INSERT INTO Fabricante VALUES (9,'Monoprix');
INSERT INTO Fabricante VALUES (10,'Gavottes');
INSERT INTO Fabricante VALUES (11,'Carrefour Bio');
INSERT INTO Fabricante VALUES (12,'Justin Bridou,Le Bâton de Berger');
INSERT INTO Fabricante VALUES (13,'Carrefour');
INSERT INTO Fabricante VALUES (14,'Sigdal,Sigdal bakeri');
INSERT INTO Fabricante VALUES (15,'Agir Carrefour,Carrefour');
INSERT INTO Fabricante VALUES (16,'Biocoop');
INSERT INTO Fabricante VALUES (17,'Nos Régions ont du Talent,Leclerc,Loc Maria');
INSERT INTO Fabricante VALUES (18,'Kaoka');
INSERT INTO Fabricante VALUES (19,'Michel et Augustin');
INSERT INTO Fabricante VALUES (20,'McVitie''s');
INSERT INTO Fabricante VALUES (21,'Vico');
INSERT INTO Fabricante VALUES (22,'Délice,Véritable Délice');
INSERT INTO Fabricante VALUES (23,'Céréal bio');
INSERT INTO Fabricante VALUES (24,'St Michel');
INSERT INTO Fabricante VALUES (25,'Kergrist');
INSERT INTO Fabricante VALUES (26,'Casino Bio');
INSERT INTO Fabricante VALUES (27,'Nos régions ont du talent');
INSERT INTO Fabricante VALUES (28,'Carabreizh');
INSERT INTO Fabricante VALUES (29,'La Maison d''Armorine');
INSERT INTO Fabricante VALUES (30,'Reflets de France,Carrefour');
INSERT INTO Fabricante VALUES (31,'Céréal Bio');
INSERT INTO Fabricante VALUES (32,'Le Moulin du Pivert');
INSERT INTO Fabricante VALUES (33,'Casino');
INSERT INTO Fabricante VALUES (34,'U');
INSERT INTO Fabricante VALUES (35,'Daco bello');
INSERT INTO Fabricante VALUES (36,'U Bio,U');
INSERT INTO Fabricante VALUES (37,'Artesani');
INSERT INTO Fabricante VALUES (38,'Isla délice');
INSERT INTO Fabricante VALUES (39,'Le collectif des gourmandes');
INSERT INTO Fabricante VALUES (40,'La Vie Claire,Les Super Kid''s');
INSERT INTO Fabricante VALUES (41,'Tuc');
INSERT INTO Fabricante VALUES (42,'Picard');
INSERT INTO Fabricante VALUES (43,'Bonneterre');
INSERT INTO Fabricante VALUES (44,'u');
INSERT INTO Fabricante VALUES (45,'McEnnedy');
INSERT INTO Fabricante VALUES (46,'Leader Price');
INSERT INTO Fabricante VALUES (47,'U Saveurs,U');
INSERT INTO Fabricante VALUES (48,'Hillcrest,Aldi');
INSERT INTO Fabricante VALUES (49,'St Michel,Saint-Michel');
INSERT INTO Fabricante VALUES (50,'Acapulco');
INSERT INTO Fabricante VALUES (51,'Dia,//Propiedad de://,Dia - Distribuidora Internacional de Alimentación S.A.');
INSERT INTO Fabricante VALUES (52,'Le Hameau');
INSERT INTO Fabricante VALUES (53,'Larnaudie,Larnaudie Prestige');
INSERT INTO Fabricante VALUES (54,'Afa Biscuiterie');
INSERT INTO Fabricante VALUES (55,'Fossier,Maison Fossier');
INSERT INTO Fabricante VALUES (56,'Tous les jours');
INSERT INTO Fabricante VALUES (57,'Top Budget,Les Mousquetaires');
INSERT INTO Fabricante VALUES (58,'Delpeyrat');
INSERT INTO Fabricante VALUES (59,'Crusti Croc');
INSERT INTO Fabricante VALUES (60,'Migros,Afiro');
INSERT INTO Fabricante VALUES (61,'Hacendado,//Propiedad de://,Mercadona S.A.');
INSERT INTO Fabricante VALUES (62,'Catago');
INSERT INTO Fabricante VALUES (63,'Ültje');
INSERT INTO Fabricante VALUES (64,'Villars');
INSERT INTO Fabricante VALUES (65,'Eugene blond');
INSERT INTO Fabricante VALUES (66,'Unser Norden');
INSERT INTO Fabricante VALUES (67,'Alnatura');
INSERT INTO Fabricante VALUES (68,'Niederegger');
INSERT INTO Fabricante VALUES (69,'La Bien Nommée');
INSERT INTO Fabricante VALUES (70,'Jardin Bio,Léa Nature');
INSERT INTO Fabricante VALUES (71,'Delicia');
INSERT INTO Fabricante VALUES (72,'Indykpol');
INSERT INTO Fabricante VALUES (73,'Lesieur');
INSERT INTO Fabricante VALUES (74,'Drizz,Aldi');
INSERT INTO Fabricante VALUES (75,'Sans marque,DV S.A.S.');
INSERT INTO Fabricante VALUES (76,'Bicentury,//Propiedad de://,Biocentury S.L.U.');
INSERT INTO Fabricante VALUES (77,'casino');
INSERT INTO Fabricante VALUES (78,'Boots');
INSERT INTO Fabricante VALUES (79,'La Trinitaine');
INSERT INTO Fabricante VALUES (80,'DOR');
INSERT INTO Fabricante VALUES (81,'Be-Kind');
INSERT INTO Fabricante VALUES (82,'Chaskis,Facundo,//Propiedad de://,Industrial Comercial Facundo S.A.');
INSERT INTO Fabricante VALUES (83,'NewTree');
INSERT INTO Fabricante VALUES (84,'Golden Bridge, GoldenBridge');
INSERT INTO Fabricante VALUES (85,'Bio Sonne');
INSERT INTO Fabricante VALUES (86,'DAO,Lou Bio');
INSERT INTO Fabricante VALUES (87,'Hollandia');
INSERT INTO Fabricante VALUES (88,'Chabrior,Sélection des Mousquetaires,Les Mousquetaires');
INSERT INTO Fabricante VALUES (89,'Mémé Georgette');
INSERT INTO Fabricante VALUES (90,'Pierre de Chaumeyrac,Marque Repère');
INSERT INTO Fabricante VALUES (91,'Cora');
INSERT INTO Fabricante VALUES (92,'Guillaume Dunoy');
INSERT INTO Fabricante VALUES (93,'Jean Larnaudie');
INSERT INTO Fabricante VALUES (94,'Guillaume Dunoy,Intermarché');
INSERT INTO Fabricante VALUES (95,'Chabrior');
INSERT INTO Fabricante VALUES (96,'Arnott''s');
INSERT INTO Fabricante VALUES (97,'CAVEOSI');
INSERT INTO Fabricante VALUES (98,'Cadbury,Mondelēz International');
INSERT INTO Fabricante VALUES (99,'Afa,Afa biscuiterie');
INSERT INTO Fabricante VALUES (100,'Dia');
INSERT INTO Fabricante VALUES (101,'Griffin''s');
INSERT INTO Fabricante VALUES (102,'Delicious Dia,Dia,//Propiedad de://,Dia - Distribuidora Internacional de Alimentación S.A.');
INSERT INTO Fabricante VALUES (103,'Argal');
INSERT INTO Fabricante VALUES (104,'Selection Terroirs Espagne');
INSERT INTO Fabricante VALUES (105,'Corte del Gusto');
INSERT INTO Fabricante VALUES (106,'Asia Green Garden');
INSERT INTO Fabricante VALUES (107,'Marks & Spencer');
INSERT INTO Fabricante VALUES (108,'Hacendado,Antiu Xixona');
INSERT INTO Fabricante VALUES (109,'Gullón');
INSERT INTO Fabricante VALUES (110,'Griesson');
INSERT INTO Fabricante VALUES (111,'Amica,Amica chips');
INSERT INTO Fabricante VALUES (112,'Flor de Navidad,//Propiedad de://,Turrones José Garrigós S.A.');
INSERT INTO Fabricante VALUES (113,'Turrón 25');
INSERT INTO Fabricante VALUES (114,'El Corte Inglés,//Propiedad de://,El Corte Inglés S.A.,//Perteneciente a://,Grupo El Corte Inglés');
INSERT INTO Fabricante VALUES (115,'El Corte Inglés');
INSERT INTO Fabricante VALUES (116,'Fleurons de Lomagne');
INSERT INTO Fabricante VALUES (117,'Pierre biscuiterie');
INSERT INTO Fabricante VALUES (118,'Netto');
INSERT INTO Fabricante VALUES (119,'Les Délices de Belle France,Belle France,Francap Distribution');
INSERT INTO Fabricante VALUES (120,'Lotus,Biscoff');
INSERT INTO Fabricante VALUES (121,'Alipende');
INSERT INTO Fabricante VALUES (122,'Virginias, B-SAN');
INSERT INTO Fabricante VALUES (123,'SuperSol');
INSERT INTO Fabricante VALUES (124,'Fontaneda');
INSERT INTO Fabricante VALUES (125,'Sondey');
INSERT INTO Fabricante VALUES (126,'Aurada');
INSERT INTO Fabricante VALUES (127,'Cuétara');
INSERT INTO Fabricante VALUES (128,'Sam Mills The Corn Master, //Propiedad de://, S.C. Sam Mills S.R.L., //Perteneciente a://, Sam Mills Group');
INSERT INTO Fabricante VALUES (129,'Real Handful');
INSERT INTO Fabricante VALUES (130,'Le Glazik');
INSERT INTO Fabricante VALUES (131,'Le Glazik,Lotus');
INSERT INTO Fabricante VALUES (132,'Chips way');
INSERT INTO Fabricante VALUES (133,'Leverno');
INSERT INTO Fabricante VALUES (134,'Newman''s Own');
INSERT INTO Fabricante VALUES (135,'Jules Destrooper');
INSERT INTO Fabricante VALUES (136,'Montfort');
INSERT INTO Fabricante VALUES (137,'Armor Délices');
INSERT INTO Fabricante VALUES (138,'Biscuiterie de l‘abbaye');
INSERT INTO Fabricante VALUES (139,'Quintesens Bio');
INSERT INTO Fabricante VALUES (140,'La Mère Poulard');
INSERT INTO Fabricante VALUES (141,'Motta');
INSERT INTO Fabricante VALUES (142,'Michel Chatillon');
INSERT INTO Fabricante VALUES (143,'Nestle');
INSERT INTO Fabricante VALUES (144,'Joannusmolen');
INSERT INTO Fabricante VALUES (145,'Ecocesta Productos Ecológicos,//Propiedad de://,Biogran S.L.');
INSERT INTO Fabricante VALUES (146,'Alipende,//Propiedad de://,AhorraMas S.A.');
INSERT INTO Fabricante VALUES (147,'goldbaums');
INSERT INTO Fabricante VALUES (148,'Bijou');
INSERT INTO Fabricante VALUES (149,'Bretagne Specialités');
INSERT INTO Fabricante VALUES (150,'Ritz,Nabisco,Mondelēz International');
INSERT INTO Fabricante VALUES (151,'Lidl,Fresh & Easy  Llc,Le Césarin Gourmand');
INSERT INTO Fabricante VALUES (152,'Casa Ramon');
INSERT INTO Fabricante VALUES (153,'Ro''thello');
INSERT INTO Fabricante VALUES (154,'Delhaize');
INSERT INTO Fabricante VALUES (155,'Cora,Groupe Louis Delhaize');
INSERT INTO Fabricante VALUES (156,'Grand Jury');
