INSERT INTO Locais_Fabricados VALUES (2,'Belgique');
INSERT INTO Locais_Fabricados VALUES (3,'France');
INSERT INTO Locais_Fabricados VALUES (4,'Bélgica ??');
INSERT INTO Locais_Fabricados VALUES (5,'Lunac');
INSERT INTO Locais_Fabricados VALUES (6,'Aveyron');
INSERT INTO Locais_Fabricados VALUES (7,'Biscuiterie de l''Abbaye - Route du Val - 61700 Lonlay-l''Abbaye');
INSERT INTO Locais_Fabricados VALUES (8,'Orne');
INSERT INTO Locais_Fabricados VALUES (9,'Normandie');
INSERT INTO Locais_Fabricados VALUES (10,'Aoste SNC - A SNC (Filiale Campofrio Food Group) - ZI Les Jacquards - 42520 Maclas');
INSERT INTO Locais_Fabricados VALUES (11,'Loire');
INSERT INTO Locais_Fabricados VALUES (12,'Rhône-Alpes');
INSERT INTO Locais_Fabricados VALUES (13,'République Tchèque');
INSERT INTO Locais_Fabricados VALUES (14,'Norvège');
INSERT INTO Locais_Fabricados VALUES (15,'Lonlay l''Abbaye');
INSERT INTO Locais_Fabricados VALUES (16,'Bretagne');
INSERT INTO Locais_Fabricados VALUES (17,'Saint-Grégoire');
INSERT INTO Locais_Fabricados VALUES (18,'United Kingdom');
INSERT INTO Locais_Fabricados VALUES (19,'Ardèche');
INSERT INTO Locais_Fabricados VALUES (20,'Finistère');
INSERT INTO Locais_Fabricados VALUES (21,'Pays-Bas');
INSERT INTO Locais_Fabricados VALUES (22,'Manche');
INSERT INTO Locais_Fabricados VALUES (23,'Champagnac de Bélair');
INSERT INTO Locais_Fabricados VALUES (24,'Italie');
INSERT INTO Locais_Fabricados VALUES (25,'Castanet-Tolosan');
INSERT INTO Locais_Fabricados VALUES (26,'België');
INSERT INTO Locais_Fabricados VALUES (27,'12270');
INSERT INTO Locais_Fabricados VALUES (28,'Suisse');
INSERT INTO Locais_Fabricados VALUES (29,'Charente Maritime');
INSERT INTO Locais_Fabricados VALUES (30,'Loc Maria');
INSERT INTO Locais_Fabricados VALUES (31,'Coray');
INSERT INTO Locais_Fabricados VALUES (32,'Australia');
INSERT INTO Locais_Fabricados VALUES (33,'Saint-Michel-Chef-Chef');
INSERT INTO Locais_Fabricados VALUES (34,'Loire-Atlantique');
INSERT INTO Locais_Fabricados VALUES (35,'Union Européenne');
INSERT INTO Locais_Fabricados VALUES (36,'Manzanares (Ciudad Real)');
INSERT INTO Locais_Fabricados VALUES (37,'Ciudad Real (provincia)');
INSERT INTO Locais_Fabricados VALUES (38,'Castilla-La Mancha');
INSERT INTO Locais_Fabricados VALUES (39,'España');
INSERT INTO Locais_Fabricados VALUES (40,'Corse');
INSERT INTO Locais_Fabricados VALUES (41,'Etablissements Berni et Cie - Rue du Port Sec - ZI de Tavannes - 55100 Verdun');
INSERT INTO Locais_Fabricados VALUES (42,'Meuse');
INSERT INTO Locais_Fabricados VALUES (43,'Lorraine');
INSERT INTO Locais_Fabricados VALUES (44,'Landes');
INSERT INTO Locais_Fabricados VALUES (45,'Royaume-Uni');
INSERT INTO Locais_Fabricados VALUES (46,'AFIRO Entreprise sociale et formatrice Lausanne');
INSERT INTO Locais_Fabricados VALUES (47,'AFIRO Ecublens Chemin de Champ Colomb 13 Case postale 25 1024 Ecublens Suisse');
INSERT INTO Locais_Fabricados VALUES (48,'Jijona');
INSERT INTO Locais_Fabricados VALUES (49,'Alicante (provincia)');
INSERT INTO Locais_Fabricados VALUES (50,'Comunidad Valenciana');
INSERT INTO Locais_Fabricados VALUES (51,'Niederlande');
INSERT INTO Locais_Fabricados VALUES (52,'Nord');
INSERT INTO Locais_Fabricados VALUES (53,'Lübeck');
INSERT INTO Locais_Fabricados VALUES (54,'Schleswig-Holstein');
INSERT INTO Locais_Fabricados VALUES (55,'Deutschland');
INSERT INTO Locais_Fabricados VALUES (56,'Belgien');
INSERT INTO Locais_Fabricados VALUES (57,'New Zealand');
INSERT INTO Locais_Fabricados VALUES (58,'Belle-Ile-en-Mer');
INSERT INTO Locais_Fabricados VALUES (59,'La Compagnie du Biscuit (Filiale Groupe Biscuits Bouvard) - 69 Avenue Jean Jaurès - 33600 Pessac');
INSERT INTO Locais_Fabricados VALUES (60,'Gironde');
INSERT INTO Locais_Fabricados VALUES (61,'Aquitaine-Limousin-Poitou-Charentes');
INSERT INTO Locais_Fabricados VALUES (62,'Allemagne');
INSERT INTO Locais_Fabricados VALUES (63,'Pologne');
INSERT INTO Locais_Fabricados VALUES (64,'02290 Montigny-Lengrain');
INSERT INTO Locais_Fabricados VALUES (65,'Aisne');
INSERT INTO Locais_Fabricados VALUES (66,'Picardie');
INSERT INTO Locais_Fabricados VALUES (67,'Quart');
INSERT INTO Locais_Fabricados VALUES (68,'Gerona (provincia)');
INSERT INTO Locais_Fabricados VALUES (69,'Cataluña');
INSERT INTO Locais_Fabricados VALUES (70,'france');
INSERT INTO Locais_Fabricados VALUES (71,'Switzerland');
INSERT INTO Locais_Fabricados VALUES (72,'U.S.A');
INSERT INTO Locais_Fabricados VALUES (73,'États-Unis');
INSERT INTO Locais_Fabricados VALUES (74,'Medina del Campo');
INSERT INTO Locais_Fabricados VALUES (75,'Valladolid (provincia)');
INSERT INTO Locais_Fabricados VALUES (76,'Castilla y León');
INSERT INTO Locais_Fabricados VALUES (77,'Villamuriel de Cerrato');
INSERT INTO Locais_Fabricados VALUES (78,'Palencia (provincia)');
INSERT INTO Locais_Fabricados VALUES (79,'Simbach am Inn');
INSERT INTO Locais_Fabricados VALUES (80,'Antersdorfer Mühle');
INSERT INTO Locais_Fabricados VALUES (81,'Provence');
INSERT INTO Locais_Fabricados VALUES (82,'Biscuits Bouvard - 73 Rue Albert Métras - ZAC de la Teppe - 01250 Ceyzériat');
INSERT INTO Locais_Fabricados VALUES (83,'Ain');
INSERT INTO Locais_Fabricados VALUES (84,'Auvergne-Rhône-Alpes');
INSERT INTO Locais_Fabricados VALUES (85,'Intario');
INSERT INTO Locais_Fabricados VALUES (86,'Canada');
INSERT INTO Locais_Fabricados VALUES (87,'Les Délices d''Auzan');
INSERT INTO Locais_Fabricados VALUES (88,'Castelnau d''Auzan');
INSERT INTO Locais_Fabricados VALUES (89,'45300 Pithivier');
INSERT INTO Locais_Fabricados VALUES (90,'ITALIE');
INSERT INTO Locais_Fabricados VALUES (91,'Canadá ??');
INSERT INTO Locais_Fabricados VALUES (92,'Industrias Cárnicas Navarras - Carretera de la Foz - s/n - 31440 Lumbier');
INSERT INTO Locais_Fabricados VALUES (93,'Navarre');
INSERT INTO Locais_Fabricados VALUES (94,'Espagne');
INSERT INTO Locais_Fabricados VALUES (95,'navarre');
INSERT INTO Locais_Fabricados VALUES (96,'espagne');
INSERT INTO Locais_Fabricados VALUES (97,'Aguilar de Campoo');
INSERT INTO Locais_Fabricados VALUES (98,'Palencia');
INSERT INTO Locais_Fabricados VALUES (99,'Amica Chips SpA Via dell''Industria 57 46043 Castiglione');
INSERT INTO Locais_Fabricados VALUES (100,'Italien');
INSERT INTO Locais_Fabricados VALUES (101,'Orgaz');
INSERT INTO Locais_Fabricados VALUES (102,'Toledo (provincia)');
INSERT INTO Locais_Fabricados VALUES (103,'61700');
INSERT INTO Locais_Fabricados VALUES (104,'Lonlay');
INSERT INTO Locais_Fabricados VALUES (105,'Bélgica');
INSERT INTO Locais_Fabricados VALUES (106,'España ?');
INSERT INTO Locais_Fabricados VALUES (107,'Villarejo de Salvanés');
INSERT INTO Locais_Fabricados VALUES (108,'Madrid');
INSERT INTO Locais_Fabricados VALUES (109,'Rumanía');
INSERT INTO Locais_Fabricados VALUES (110,'Briec');
INSERT INTO Locais_Fabricados VALUES (111,'Serbia');
INSERT INTO Locais_Fabricados VALUES (112,'61700 LONLAY L''ABBAYE');
INSERT INTO Locais_Fabricados VALUES (113,'Poland');
INSERT INTO Locais_Fabricados VALUES (114,'Hulsbos 3');
INSERT INTO Locais_Fabricados VALUES (115,'5431 NZ Cuijk');
INSERT INTO Locais_Fabricados VALUES (116,'Nederland');
INSERT INTO Locais_Fabricados VALUES (117,'[DISTRIBUIDOR]');
INSERT INTO Locais_Fabricados VALUES (118,'israel');
INSERT INTO Locais_Fabricados VALUES (119,'87500');
INSERT INTO Locais_Fabricados VALUES (120,'Brocéliande-ALH (Filiale Cooperl Arc Atlantique) - Rue du Moulin Tampon - 42120 Perreux');
INSERT INTO Locais_Fabricados VALUES (121,'Hungary');
INSERT INTO Locais_Fabricados VALUES (122,'A SNC Hameau de Saint-Didier RD 592 38400 Les Abrets France');
INSERT INTO Locais_Fabricados VALUES (123,'Ungarn');
INSERT INTO Locais_Fabricados VALUES (124,'Intersnack France - ISF (Filiale Groupe Intersnack) - Route de Compiègne - 02290 Montigny-Lengrain');
