INSERT INTO Locais_Vendidos VALUES (2,'France');
INSERT INTO Locais_Vendidos VALUES (3,'Espagne');
INSERT INTO Locais_Vendidos VALUES (4,'Suisse');
INSERT INTO Locais_Vendidos VALUES (5,'Australie');
INSERT INTO Locais_Vendidos VALUES (6,'Guadeloupe');
INSERT INTO Locais_Vendidos VALUES (7,'Denmark');
INSERT INTO Locais_Vendidos VALUES (8,'Switzerland');
INSERT INTO Locais_Vendidos VALUES (9,'Belgium');
INSERT INTO Locais_Vendidos VALUES (10,'Spain');
INSERT INTO Locais_Vendidos VALUES (11,'Sweden');
INSERT INTO Locais_Vendidos VALUES (12,'Finland');
INSERT INTO Locais_Vendidos VALUES (13,'Australia');
INSERT INTO Locais_Vendidos VALUES (14,'España');
INSERT INTO Locais_Vendidos VALUES (15,'Deutschland');
INSERT INTO Locais_Vendidos VALUES (16,'Schweiz');
INSERT INTO Locais_Vendidos VALUES (17,'Germany');
INSERT INTO Locais_Vendidos VALUES (18,'United Kingdom');
INSERT INTO Locais_Vendidos VALUES (19,'États-Unis');
INSERT INTO Locais_Vendidos VALUES (20,'Belgique');
INSERT INTO Locais_Vendidos VALUES (21,'Canada');
INSERT INTO Locais_Vendidos VALUES (22,'Allemagne');
INSERT INTO Locais_Vendidos VALUES (23,'New Zealand');
INSERT INTO Locais_Vendidos VALUES (24,'Portugal');
INSERT INTO Locais_Vendidos VALUES (25,'Italie');
INSERT INTO Locais_Vendidos VALUES (26,'United States');
INSERT INTO Locais_Vendidos VALUES (27,'Francia');
INSERT INTO Locais_Vendidos VALUES (28,'Serbia');
INSERT INTO Locais_Vendidos VALUES (29,'Nederland');
INSERT INTO Locais_Vendidos VALUES (30,'Frankreich');
